/**
 * Enum representing the different strategies for handling ID creation.
 *
 * @enum {string}
 */
export enum CreateIdOption {
  /** Automatically generates a unique ID. */
  AutoGeneratedId = "AutoGeneratedId",

  /** Allows manual ID creation with the possibility of conflicts. */
  ManualAllowIdConflicts = "ManualAllowIdConflicts",

  /** Requires manual ID creation but rejects any conflicts. */
  ManualRejectIdConflicts = "ManualRejectIdConflicts",
}
